# Generated by Django 5.1.3 on 2024-12-01 17:58

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_by', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='previously_done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='suggested_follow_ups',
            field=models.ManyToManyField(blank=True, related_name='suggested_for', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='Exterior', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='typical_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, validators=[tasks.models.validate_youtube_url]),
        ),
    ]
